"""Validate bundled car templates: every ACR car carries the canonical tyre list,
separate front/rear pressure parameters, and never a combined "Tyre Pressure" row.

Requires PyYAML (see requirements-dev.txt).

Run: python -m unittest discover tests   (or: python tests/test_car_templates.py)
"""
import glob
import os
import re
import sys
import unittest

import yaml

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'tools', 'car-catalog'))

TEMPLATES_DIR = os.path.join(os.path.dirname(__file__), '..', '.claude', 'skills',
                              'acr-setup-engineer', 'car-templates')

CANONICAL_TYRES = [
    'Tarmac Soft', 'Tarmac Medium', 'Tarmac Hard', 'Tarmac Wet', 'Tarmac Winter',
    'Tarmac Snow', 'Gravel Soft', 'Gravel Medium', 'Gravel Hard', 'Snow (Studs)',
]


def load_templates():
    paths = sorted(glob.glob(os.path.join(TEMPLATES_DIR, '*.yaml')))
    docs = []
    for path in paths:
        with open(path, encoding='utf-8') as f:
            docs.append((path, yaml.safe_load(f)))
    return docs


class TestCarTemplates(unittest.TestCase):
    def test_templates_found(self):
        self.assertTrue(load_templates(), f'no *.yaml templates found in {TEMPLATES_DIR}')

    def test_acr_templates_have_canonical_tyre_list(self):
        for path, doc in load_templates():
            if doc.get('game') != 'ACR':
                continue
            with self.subTest(template=os.path.basename(path)):
                params = doc['parameters']
                tyre_rows = [p for p in params if p.get('adjustment') == 'Tyre Type']
                self.assertEqual(
                    len(tyre_rows), 1,
                    f'expected exactly one "Tyre Type" row, found {len(tyre_rows)}')
                steps = [s.strip() for s in tyre_rows[0]['discrete_steps'].split(',')]
                self.assertEqual(steps, CANONICAL_TYRES)

    def test_acr_templates_have_separate_front_rear_pressure(self):
        for path, doc in load_templates():
            if doc.get('game') != 'ACR':
                continue
            with self.subTest(template=os.path.basename(path)):
                adjustments = {p.get('adjustment') for p in doc['parameters']}
                self.assertIn('Pressure Front', adjustments)
                self.assertIn('Pressure Rear', adjustments)
                self.assertNotIn('Tyre Pressure', adjustments,
                                  'pressure must be split into Pressure Front/Rear, '
                                  'never a single combined "Tyre Pressure" row')

    def test_parameters_have_required_fields(self):
        for path, doc in load_templates():
            with self.subTest(template=os.path.basename(path)):
                for param in doc['parameters']:
                    self.assertIsInstance(param, dict)
                    for field in ('section', 'adjustment', 'order'):
                        self.assertIn(field, param, f'missing "{field}" in {param}')

    def test_engine_curve_is_well_formed(self):
        """The engine_curve block is generated by tools/torque-curves from the ACR game
        files. It's optional (a community-exported template won't have one), but when it
        is present the chart URL, the summary lines and the points must agree."""
        for path, doc in load_templates():
            curve = doc.get('engine_curve')
            if curve is None:
                self.assertNotIn('power_torque_chart', doc,
                                 'a chart URL without an engine_curve block')
                continue
            slug = os.path.basename(path)[:-len('.yaml')]
            with self.subTest(template=os.path.basename(path)):
                self.assertTrue(
                    doc.get('power_torque_chart', '').endswith(f'/{slug}-power-torque.png'),
                    'chart URL must point at the PNG named for this template')

                points = curve['torque_points']
                self.assertGreaterEqual(len(points), 20)
                rpms = [p[0] for p in points]
                self.assertEqual(rpms, sorted(set(rpms)), 'rpm must strictly increase')
                steps = {b - a for a, b in zip(rpms, rpms[1:])}
                self.assertEqual(steps, {curve['rpm_step']}, 'uneven rpm sampling')

                peak_nm, peak_rpm = max(points, key=lambda p: p[1])[::-1]
                self.assertEqual(curve['peak_torque'], f'{round(peak_nm)} Nm at {peak_rpm} rpm')

                # metric hp; matches tools/torque-curves/extract_torque_curves.py
                power = [(r, nm * r / 9549.0 * 1.35962) for r, nm in points]
                p_rpm, p_hp = max(power, key=lambda x: x[1])
                self.assertEqual(curve['peak_power'], f'{round(p_hp)} hp at {p_rpm} rpm')


    def test_templates_have_gearing_tool_link_and_no_removed_chart_keys(self):
        """Per-car gearing and final-drive PNG charts were replaced by a link to the
        car's page in the ACR Car Lab. Every bundled template must carry a
        `gearing_tool` URL built from its own filename stem, and none may still carry
        the removed `gearing_chart` / `final_drive_chart` keys."""
        for path, doc in load_templates():
            slug = os.path.basename(path)[:-len('.yaml')]
            with self.subTest(template=os.path.basename(path)):
                self.assertEqual(
                    doc.get('gearing_tool'),
                    f'https://fredmayor88.github.io/acr-car-lab/{slug}/gears/',
                    'gearing_tool must point at this template\'s own ACR Car Lab page')
                self.assertNotIn('gearing_chart', doc,
                                  'gearing_chart was replaced by gearing_tool')
                self.assertNotIn('final_drive_chart', doc,
                                  'final_drive_chart was replaced by gearing_tool')

    def test_bootstrap_header_carries_a_gearing_tool_link(self):
        """A brand-new car's starter header must already carry `gearing_tool:`, built from the
        car's slug against the same ACR Car Lab base every bundled template uses — otherwise
        test_templates_have_gearing_tool_link_and_no_removed_chart_keys fails on the next new
        car and the field has to be added by hand."""
        import extract_car_catalog as E
        header = E.bootstrap_header('lancia-stratos')
        self.assertIn(
            'gearing_tool: "https://fredmayor88.github.io/acr-car-lab/lancia-stratos/gears/"',
            header)
        # it belongs in the header block, after `source:` — where refresh_header keeps it
        self.assertLess(header.index('source:'), header.index('gearing_tool:'))
        self.assertTrue(yaml.safe_load(header))

    def test_templates_declare_where_their_values_came_from(self):
        """`source` records where a template's values came from: `game-files` for the
        maintainer's extracted templates, `community` for a user's export. Every bundled
        template is extracted from the ACR game files, so all 18 say `game-files`."""
        for path, doc in load_templates():
            with self.subTest(template=os.path.basename(path)):
                self.assertIn(doc.get('source'), ('game-files', 'community'),
                              'source must be "game-files" or "community"')
                self.assertEqual(doc['source'], 'game-files',
                                 'every bundled template is extracted from the game files')

    def test_the_extractor_maintains_version_and_source_on_a_rewrite(self):
        """tools/car-catalog rewrites a template's rows and keeps its header in line:
        the game version, and `source: "game-files"` right after it — inserted when the
        template predates the field, and never confused with the indented `source:` inside
        the engine_curve block."""
        from extract_car_catalog import GAME_VERSION, refresh_header

        old = ('car: "Test Car"\n'
               'version: "0.1"\n'
               'gearing_tool: "https://example.invalid/test/gears/"\n'
               'engine_curve:\n'
               '  source: "ACR game files - FC_Test_Torque"')
        refreshed = refresh_header(old)
        self.assertIn(f'version: "{GAME_VERSION}"\nsource: "game-files"\n', refreshed)
        self.assertIn('  source: "ACR game files - FC_Test_Torque"', refreshed)
        self.assertEqual(refreshed.count('source: "game-files"'), 1)

        # already carries the field (any value) -> corrected in place, not duplicated
        again = refresh_header(refreshed.replace('source: "game-files"', 'source: "community"'))
        self.assertEqual(again.count('source:'), 2)         # ours + the engine_curve one
        self.assertIn('source: "game-files"', again)

    def test_compound_gear_values_keep_their_asterisk(self):
        """A two-stage primary drive is spelled `A//B*C//D`. Because `*` is markdown
        emphasis, a value that round-trips through an unprotected markdown context comes
        back as `35//3033//28` — asterisks eaten, matching nothing in the catalog. The
        templates are the source these get repaired from, so they must never carry the
        collapsed form (SKILL.md -> Compound gear values)."""
        compound = re.compile(r'^\d+//\d+\*\d+//\d+$')
        seen = 0
        for path, doc in load_templates():
            with self.subTest(template=os.path.basename(path)):
                for param in doc['parameters']:
                    steps = param.get('discrete_steps') or ''
                    for value in (v.strip() for v in steps.split(',')):
                        # two ratio pairs in one value means a compound primary drive
                        if value.count('//') < 2:
                            continue
                        seen += 1
                        self.assertRegex(
                            value, compound,
                            f'{param["adjustment"]}: compound gear value {value!r} must be '
                            f'spelled A//B*C//D with the asterisk intact')
        # guard the guard: if the notation ever changes shape, this test must not
        # silently start checking nothing.
        self.assertGreater(seen, 0, 'no compound gear values found in any template')


if __name__ == '__main__':
    unittest.main()
