"""Validate bundled car templates: every ACR car carries the canonical tyre list,
separate front/rear pressure parameters, and never a combined "Tyre Pressure" row.

Requires PyYAML (see requirements-dev.txt).

Run: python -m unittest discover tests   (or: python tests/test_car_templates.py)
"""
import glob
import os
import unittest

import yaml

TEMPLATES_DIR = os.path.join(os.path.dirname(__file__), '..', '.claude', 'skills',
                              'acr-setup-engineer', 'car-templates')

CANONICAL_TYRES = [
    'Tarmac Soft', 'Tarmac Medium', 'Tarmac Hard', 'Tarmac Wet', 'Tarmac Winter',
    'Tarmac Snow', 'Gravel Soft', 'Gravel Medium', 'Gravel Hard', 'Snow (Studs)',
]


def load_templates():
    paths = sorted(glob.glob(os.path.join(TEMPLATES_DIR, '*.yaml')))
    docs = []
    for path in paths:
        with open(path, encoding='utf-8') as f:
            docs.append((path, yaml.safe_load(f)))
    return docs


class TestCarTemplates(unittest.TestCase):
    def test_templates_found(self):
        self.assertTrue(load_templates(), f'no *.yaml templates found in {TEMPLATES_DIR}')

    def test_acr_templates_have_canonical_tyre_list(self):
        for path, doc in load_templates():
            if doc.get('game') != 'ACR':
                continue
            with self.subTest(template=os.path.basename(path)):
                params = doc['parameters']
                tyre_rows = [p for p in params if p.get('adjustment') == 'Tyre Type']
                self.assertEqual(
                    len(tyre_rows), 1,
                    f'expected exactly one "Tyre Type" row, found {len(tyre_rows)}')
                steps = [s.strip() for s in tyre_rows[0]['discrete_steps'].split(',')]
                self.assertEqual(steps, CANONICAL_TYRES)

    def test_acr_templates_have_separate_front_rear_pressure(self):
        for path, doc in load_templates():
            if doc.get('game') != 'ACR':
                continue
            with self.subTest(template=os.path.basename(path)):
                adjustments = {p.get('adjustment') for p in doc['parameters']}
                self.assertIn('Pressure Front', adjustments)
                self.assertIn('Pressure Rear', adjustments)
                self.assertNotIn('Tyre Pressure', adjustments,
                                  'pressure must be split into Pressure Front/Rear, '
                                  'never a single combined "Tyre Pressure" row')

    def test_parameters_have_required_fields(self):
        for path, doc in load_templates():
            with self.subTest(template=os.path.basename(path)):
                for param in doc['parameters']:
                    self.assertIsInstance(param, dict)
                    for field in ('section', 'adjustment', 'order'):
                        self.assertIn(field, param, f'missing "{field}" in {param}')

    def test_engine_curve_is_well_formed(self):
        """The engine_curve block is generated by tools/torque-curves from the ACR game
        files. It's optional (a community-exported template won't have one), but when it
        is present the chart URL, the summary lines and the points must agree."""
        for path, doc in load_templates():
            curve = doc.get('engine_curve')
            if curve is None:
                self.assertNotIn('power_torque_chart', doc,
                                 'a chart URL without an engine_curve block')
                continue
            slug = os.path.basename(path)[:-len('.yaml')]
            with self.subTest(template=os.path.basename(path)):
                self.assertTrue(
                    doc.get('power_torque_chart', '').endswith(f'/{slug}-power-torque.png'),
                    'chart URL must point at the PNG named for this template')

                points = curve['torque_points']
                self.assertGreaterEqual(len(points), 20)
                rpms = [p[0] for p in points]
                self.assertEqual(rpms, sorted(set(rpms)), 'rpm must strictly increase')
                steps = {b - a for a, b in zip(rpms, rpms[1:])}
                self.assertEqual(steps, {curve['rpm_step']}, 'uneven rpm sampling')

                peak_nm, peak_rpm = max(points, key=lambda p: p[1])[::-1]
                self.assertEqual(curve['peak_torque'], f'{round(peak_nm)} Nm at {peak_rpm} rpm')

                # metric hp; matches tools/torque-curves/extract_torque_curves.py
                power = [(r, nm * r / 9549.0 * 1.35962) for r, nm in points]
                p_rpm, p_hp = max(power, key=lambda x: x[1])
                self.assertEqual(curve['peak_power'], f'{round(p_hp)} hp at {p_rpm} rpm')


if __name__ == '__main__':
    unittest.main()
