#!/usr/bin/env python3
"""Extract every car's engine torque curve from the ACR game files, render a
power/torque chart per car, and write the curve back into the bundled car templates.

Maintainer tooling — it needs a local Assetto Corsa Rally install and is never shipped
inside the skill. See README.md in this folder for setup and the data provenance.

    python extract_torque_curves.py              # charts + template updates
    python extract_torque_curves.py --dry-run    # report only, touch nothing
"""

import argparse
import json
import os
import re
import struct
import subprocess
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from iostore import Toc  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))

DEFAULT_PAKS = ("C:/Program Files (x86)/Steam/steamapps/common/"
                "Assetto Corsa Rally/acr/Content/Paks")

CHART_URL_BASE = ("https://raw.githubusercontent.com/fredmayor88/acr-setup-engineer/"
                  "main/car-charts")

# In-game asset folder -> (slug, display name). The slug names both the chart file and
# the bundled template. A car with no template yet still gets a chart; the curve simply
# has nowhere to be written until someone onboards it (e.g. the Peugeot 208 Rally4).
CAR_MAP = {
    "AlfaRomeoGiuliaGTA1300Junior": ("alfa-romeo-gta-1300-junior-1972", "Alfa Romeo GTA 1300 Junior 1972"),
    "AlpineA110":               ("alpine-a110-1-8-1973", "Alpine A110 1.8 1973"),
    "CitroenXsaraWRC":              ("citroen-xsara-wrc-2003", "Citroen Xsara WRC 2003"),
    "Fiat124Abarth":                ("fiat-124-abarth-rally-16v-1974", "Fiat 124 Abarth Rally 16V 1974"),
    "Fiat131Abarth":                ("fiat-131-abarth-1976", "Fiat 131 Abarth 1976"),
    "HyundaiI20NRally2":            ("hyundai-i20-rally2-2021", "Hyundai i20 Rally2 2021"),
    "LanciaDeltaHFIntegraleEvo":    ("lancia-delta-integrale-evoluzione-1992", "Lancia Delta Integrale Evoluzione 1992"),
    "LanciaFulviaCoupeHF": ("lancia-fulvia-coupe-hf-1970", "Lancia Fulvia Coupe HF 1970"),
    "LanciaRally037Evo2":           ("lancia-037-evoluzione-2-1984", "Lancia 037 Evoluzione 2 1984"),
    "LanciaStratosHF":              ("lancia-stratos", "Lancia Stratos HF 1976"),
    "MiniCooperS1275":              ("mini-cooper-s-1964", "Mini Cooper S 1964"),
    "Peugeot208Rally4":             ("peugeot-208-rally4", "Peugeot 208 Rally4"),
    "Peugeot306IIMaxi":       ("peugeot-306-ii-maxi-1997", "Peugeot 306 II Maxi 1997"),
    "SkodaFabiaRSRally2":           ("skoda-fabia-rs-rally2-2022", "Skoda Fabia RS Rally2 2022"),
    "SubaruImprezaS3":           ("subaru-impreza-555-s3-1993", "Subaru Impreza 555 (S3) 1993"),
    "AudiQuattroGr4":               ("audi-quattro-gr4-1981", "Audi Quattro Gr4 1981"),
    "VWPoloGTIR5":                  ("volkswagen-polo-gti-r5-2018", "Volkswagen Polo GTI R5 2018"),
    # Peugeot206WRC has no FC_*_Torque asset in the game files yet (see
    # car-catalog/README.md - Car identity facts / the Peugeot 206 WRC note) -
    # this entry is a no-op until the game ships one, at which point charting
    # picks it up automatically.
    "Peugeot206WRC":                ("peugeot-206-wrc-1999", "Peugeot 206 WRC 1999"),
}

# Brand palette (yt-writing/brand-palette.md)
WARM_WHITE, GRAPHITE, DARK_GRAPHITE = "#F5F2EB", "#30353A", "#212529"
STEEL, WALNUT, DEEP_CYAN = "#7B858E", "#7A583B", "#148FAC"

BLOCK_START = "# --- engine curve (generated by tools/torque-curves) ---"
BLOCK_END = "# --- end engine curve ---"

# A serialised FRichCurveKey: InterpMode, TangentMode, TangentWeightMode (1 byte each),
# then Time, Value, ArriveTangent, LeaveTangent, ArriveTangentWeight, LeaveTangentWeight.
KEY_SIZE = 27


def find_curve_assets(paks):
    """Every FC_*_Torque.uasset in the game's pak files, keyed by car folder."""
    found = {}
    for entry in sorted(os.listdir(paks)):
        if not entry.endswith(".utoc"):
            continue
        try:
            toc = Toc(os.path.join(paks, entry))
            listing = toc.files()
        except Exception:
            continue  # a few paks use container formats we don't parse; none hold vehicle data
        for path, idx in listing.items():
            base = os.path.basename(path)
            if not (base.startswith("FC_") and base.endswith("_Torque.uasset")):
                continue
            m = re.search(r"/Vehicles/([^/]+)/", path)
            if m:
                found[m.group(1)] = (toc, entry, idx, path)
    return found


def parse_rich_curve(data):
    """Recover the key list from an unversioned-property FRichCurve blob.

    ACR ships with unversioned property serialisation, so there are no name tags to
    anchor on. Instead we scan for a plausible int32 count followed by that many
    27-byte keys with strictly increasing, in-range times, and keep the longest match.
    """
    best = None
    for off in range(len(data) - 4):
        n = struct.unpack_from("<I", data, off)[0]
        if not 4 <= n <= 300 or off + 4 + n * KEY_SIZE > len(data):
            continue
        keys, prev, ok = [], -1.0, True
        for k in range(n):
            rpm, nm = struct.unpack_from("<ff", data, off + 4 + k * KEY_SIZE + 3)
            if not 0.0 <= rpm <= 20000.0 or (k and rpm <= prev) or not -2000.0 <= nm <= 5000.0:
                ok = False
                break
            prev = rpm
            keys.append((rpm, nm))
        if ok and (best is None or len(keys) > len(best)):
            best = keys
    return best


def unpack_chunks(jobs):
    """Hand the block plans to node/ooz-wasm, which does the Oodle decode."""
    with tempfile.NamedTemporaryFile("w", suffix=".json", delete=False) as fh:
        json.dump(jobs, fh)
        job_path = fh.name
    try:
        subprocess.run(["node", os.path.join(HERE, "ooz_unpack.mjs"), job_path],
                       check=True, cwd=HERE)
    finally:
        os.unlink(job_path)


def hp(rpm, nm):
    """Crank power in metric hp. kW = Nm x rpm / 9549."""
    return nm * rpm / 9549.0 * 1.35962


def summarise(keys):
    pts = [(int(round(r)), round(v, 1)) for r, v in keys]
    powers = [(r, hp(r, v)) for r, v in pts]
    t_rpm, t_nm = max(pts, key=lambda x: x[1])
    p_rpm, p_hp = max(powers, key=lambda x: x[1])
    return {
        "points": pts,
        "peak_torque_nm": round(t_nm), "peak_torque_rpm": t_rpm,
        "peak_power_hp": round(p_hp), "peak_power_rpm": p_rpm,
        "rpm_step": pts[1][0] - pts[0][0],
        "max_rpm": pts[-1][0],
    }


def render_chart(car_name, s, out_path):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from matplotlib.ticker import FuncFormatter, MultipleLocator

    rpm = [p[0] for p in s["points"]]
    nm = [p[1] for p in s["points"]]
    power = [hp(r, v) for r, v in s["points"]]

    fig, ax_t = plt.subplots(figsize=(10, 5.4), dpi=160)
    fig.patch.set_facecolor(WARM_WHITE)
    ax_t.set_facecolor(WARM_WHITE)
    ax_p = ax_t.twinx()

    ax_t.plot(rpm, nm, color=WALNUT, lw=2.6, zorder=3, solid_capstyle="round")
    ax_t.fill_between(rpm, nm, color=WALNUT, alpha=0.09, zorder=1)
    ax_p.plot(rpm, power, color=DEEP_CYAN, lw=2.6, zorder=3, solid_capstyle="round")

    for ax, colour, label, top in ((ax_t, WALNUT, "Torque  (Nm)", max(nm)),
                                   (ax_p, DEEP_CYAN, "Power  (hp)", max(power))):
        ax.set_ylim(0, top * 1.18)
        ax.set_ylabel(label, color=colour, fontsize=10.5, labelpad=9)
        ax.tick_params(axis="y", colors=colour, labelsize=9.5, length=0)
        for side in ("top", "left", "right"):
            ax.spines[side].set_visible(False)

    ax_t.set_xlim(0, s["max_rpm"])
    ax_t.xaxis.set_major_locator(MultipleLocator(1000))
    ax_t.xaxis.set_major_formatter(FuncFormatter(lambda v, _: f"{int(v):,}"))
    ax_t.set_xlabel("Engine speed  (rpm)", color=GRAPHITE, fontsize=10.5, labelpad=8)
    ax_t.tick_params(axis="x", colors=GRAPHITE, labelsize=9.5, length=0)
    ax_t.grid(axis="both", color=STEEL, alpha=0.22, lw=0.7, zorder=0)
    ax_t.set_axisbelow(True)
    ax_t.spines["bottom"].set_color(STEEL)
    ax_t.spines["bottom"].set_alpha(0.45)

    # peak markers
    ax_t.plot(s["peak_torque_rpm"], s["peak_torque_nm"], "o", ms=6,
              color=WARM_WHITE, mec=WALNUT, mew=2.2, zorder=5)
    ax_t.annotate(f"{s['peak_torque_nm']} Nm\n{s['peak_torque_rpm']:,} rpm",
                  (s["peak_torque_rpm"], s["peak_torque_nm"]), textcoords="offset points",
                  xytext=(0, 14), ha="center", fontsize=9.5, color=WALNUT, weight="bold")
    ax_p.plot(s["peak_power_rpm"], s["peak_power_hp"], "o", ms=6,
              color=WARM_WHITE, mec=DEEP_CYAN, mew=2.2, zorder=5)
    ax_p.annotate(f"{s['peak_power_hp']} hp\n{s['peak_power_rpm']:,} rpm",
                  (s["peak_power_rpm"], s["peak_power_hp"]), textcoords="offset points",
                  xytext=(0, 14), ha="center", fontsize=9.5, color=DEEP_CYAN, weight="bold")

    fig.text(0.045, 0.955, car_name, fontsize=17, weight="bold",
             color=DARK_GRAPHITE, ha="left", va="top")
    fig.text(0.045, 0.905, "Engine output, Assetto Corsa Rally game data",
             fontsize=9.5, color=STEEL, ha="left", va="top")
    fig.text(0.955, 0.028, "Driver's Infrastructure", fontsize=8.5,
             color=STEEL, alpha=0.8, ha="right", va="bottom")

    fig.subplots_adjust(left=0.075, right=0.925, top=0.80, bottom=0.135)
    fig.savefig(out_path, facecolor=WARM_WHITE)
    plt.close(fig)


def yaml_block(slug, asset_name, s):
    """The generated stanza written into a car template, delimited so it can be replaced."""
    pts = ", ".join(f"[{r}, {v:g}]" for r, v in s["points"])
    wrapped, line = [], "    "
    for chunk in pts.split("], "):
        chunk = chunk if chunk.endswith("]") else chunk + "]"
        if len(line) + len(chunk) > 96 and line.strip():
            wrapped.append(line.rstrip())
            line = "    "
        line += chunk + ", "
    wrapped.append(line.rstrip().rstrip(","))

    lines = [
        BLOCK_START,
        f'power_torque_chart: "{CHART_URL_BASE}/{slug}-power-torque.png"',
        "engine_curve:",
        f'  source: "ACR game files - {asset_name}"',
        f'  peak_torque: "{s["peak_torque_nm"]} Nm at {s["peak_torque_rpm"]} rpm"',
        f'  peak_power: "{s["peak_power_hp"]} hp at {s["peak_power_rpm"]} rpm"',
        f'  rpm_step: {s["rpm_step"]}',
        "  # [rpm, Nm] straight from the game's engine curve; power is derived, not stored.",
        "  torque_points: [",
    ]
    lines += wrapped
    lines += ["  ]", BLOCK_END]
    return "\n".join(lines) + "\n"


# tools/gearing-charts writes these two lines into the same BLOCK_START..BLOCK_END
# span (it imports BLOCK_START/BLOCK_END from here on purpose). yaml_block() never
# emits them itself, so a plain regex swap of the whole span silently deletes them
# if that tool ran first - carry them forward instead of overwriting them.
CHART_LINE_RE = re.compile(r'^(gearing_chart|final_drive_chart): .*$\n?', re.MULTILINE)


# The exact placeholder car-catalog's bootstrap_header() writes for a brand-new car -
# matched verbatim so a real, human-entered spec is never overwritten.
_TODO_POWER = 'max_power: "TODO - real-world spec (see README.md: this is not game output)"'
_TODO_TORQUE = 'max_torque: "TODO - real-world spec (see README.md: this is not game output)"'


def backfill_todo_specs(text, s):
    """Replace car-catalog's bootstrap max_power/max_torque TODOs with the game's
    own engine-curve peaks, clearly labelled as such - the numbers are real ACR
    output, not a guess, but README.md's own note applies: on forced-induction
    cars the game's simulated peak and the real-world spec can genuinely differ,
    so this is a starting value to confirm against a spec sheet, not a final one.
    Never touches a line a human has already filled in.
    """
    text = text.replace(_TODO_POWER,
        f'max_power: "{s["peak_power_hp"]} hp at {s["peak_power_rpm"]} rpm '
        f'(ACR engine-curve peak - see engine_curve: below; confirm against a real-world spec sheet)"')
    text = text.replace(_TODO_TORQUE,
        f'max_torque: "{s["peak_torque_nm"]} Nm at {s["peak_torque_rpm"]} rpm '
        f'(ACR engine-curve peak - see engine_curve: below; confirm against a real-world spec sheet)"')
    return text


def write_template(path, block, s=None):
    text = open(path, encoding="utf-8").read()
    pattern = re.compile(re.escape(BLOCK_START) + r"(.*?)" + re.escape(BLOCK_END) + r"\n",
                         re.DOTALL)
    m = pattern.search(text)
    if m:
        carried = [ln.group(0) for ln in CHART_LINE_RE.finditer(m.group(1))]
        if carried:
            after = f'power_torque_chart: "{CHART_URL_BASE}'
            idx = block.index("\n", block.index(after)) + 1
            block = block[:idx] + "".join(carried) + block[idx:]
        text = text[:m.start()] + block + text[m.end():]
    else:
        # sits between the identity facts and the tunable parameter list
        text = text.replace("\nparameters:", "\n" + block + "\nparameters:", 1)
    if s is not None:
        text = backfill_todo_specs(text, s)
    open(path, "w", encoding="utf-8", newline="\n").write(text)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--paks", default=DEFAULT_PAKS, help="ACR Content/Paks folder")
    ap.add_argument("--charts", default=os.path.join(REPO, "car-charts"))
    ap.add_argument("--templates",
                    default=os.path.join(REPO, ".claude", "skills", "acr-setup-engineer", "car-templates"))
    ap.add_argument("--dry-run", action="store_true", help="report only; write nothing")
    args = ap.parse_args()

    if not os.path.isdir(args.paks):
        sys.exit(f"ACR paks not found at {args.paks} (pass --paks)")

    assets = find_curve_assets(args.paks)
    print(f"found {len(assets)} torque curves in {args.paks}\n")

    work = tempfile.mkdtemp(prefix="acr-torque-")
    jobs, order = [], []
    for car, (toc, toc_name, idx, path) in sorted(assets.items()):
        job = toc.plan(idx, os.path.join(args.paks, toc_name.replace(".utoc", ".ucas")))
        job["out"] = os.path.join(work, car + ".bin")
        jobs.append(job)
        order.append((car, os.path.basename(path).replace(".uasset", "")))
    unpack_chunks(jobs)

    if not args.dry_run:
        os.makedirs(args.charts, exist_ok=True)

    no_template, written, charted = [], 0, 0
    for car, asset_name in order:
        keys = parse_rich_curve(open(os.path.join(work, car + ".bin"), "rb").read())
        if not keys:
            print(f"  !! {car}: could not parse a curve")
            continue
        s = summarise(keys)
        if car not in CAR_MAP:
            print(f"  !! {car}: not in CAR_MAP - add it and re-run")
            continue
        slug, display = CAR_MAP[car]

        if not args.dry_run:
            render_chart(display, s, os.path.join(args.charts, f"{slug}-power-torque.png"))
        charted += 1

        tpl = os.path.join(args.templates, f"{slug}.yaml")
        has_tpl = os.path.exists(tpl)
        if not has_tpl:
            no_template.append(display)

        print(f"  {display:<40} {len(s['points']):>3} pts  "
              f"{s['peak_torque_nm']:>4} Nm @ {s['peak_torque_rpm']:>5}  "
              f"{s['peak_power_hp']:>4} hp @ {s['peak_power_rpm']:>5}"
              f"{'' if has_tpl else '   (no template - chart only)'}")

        if has_tpl and not args.dry_run:
            write_template(tpl, yaml_block(slug, asset_name, s), s)
            written += 1

    # charts are only written for cars in CAR_MAP, so this is not len(order)
    print(f"\n{'would write' if args.dry_run else 'wrote'} {charted} charts, "
          f"{written} template updates")
    if no_template:
        print("no bundled template yet (chart generated anyway): " + ", ".join(no_template))


if __name__ == "__main__":
    main()
